apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-account-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-account
  template:
    metadata:
      labels:
        app: user-account
    spec:
      containers:
        - name: user-account
          image: shahzaibshaikh/user-account
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: SECRET_KEY
            - name: MONGO_URI_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-uri-secret-user
                  key: MONGO_URI_USER
---
apiVersion: v1
kind: Service
metadata:
  name: user-account-srv
spec:
  selector:
    app: user-account
  ports:
    - name: user-account
      protocol: TCP
      port: 3006
      targetPort: 3006
